import React from 'react';
import { connect } from 'react-redux';
import ErrorBoundry from './ErrorBoundry/index';
import VisibleSearch from './Search/duck/container';
// import VisibleVisualization from './Visualization/duck/container';
import Visualization from './Visualization/index';
import './weather-icons/css/weather-icons.css';
import './sass/main.scss';

const mapStateToProps = (state) => {
  return {
    // TODO: Uncomment after fix styling
    // data: state.searchReducer.data,
    data: tempdata
  };
};

const App = ({ data }) => {
  console.log(data);
  return (
    <div className="app">
      <ErrorBoundry>
        <VisibleSearch />
        {
          data.length > 0 ? <Visualization data={ data } /> : void 0
        }

      </ErrorBoundry>
    </div>
  );
};

// export default App;
export default connect(mapStateToProps, null)(App);

let data1 = {
   "request":[
      {
         "type":"City",
         "query":"Honolulu, United States of America"
      }
   ],
   "weather":[
      {
         "date":"2017-04-02",
         "astronomy":[
            {
               "sunrise":"06:23 AM",
               "sunset":"06:47 PM",
               "moonrise":"11:23 AM",
               "moonset":"No moonset",
               "moon_phase":"Waxing Crescent",
               "moon_illumination":"21"
            }
         ],
         "maxtempC":"29",
         "maxtempF":"84",
         "mintempC":"25",
         "mintempF":"76",
         "totalSnow_cm":"0.0",
         "sunHour":"0.0",
         "uvIndex":"0",
         "hourly":[
            {
               "time":"24",
               "tempC":"29",
               "tempF":"84",
               "windspeedMiles":"18",
               "windspeedKmph":"29",
               "winddirDegree":"77",
               "winddir16Point":"ENE",
               "weatherCode":"113",
               "weatherIconUrl":[
                  {
                     "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                  }
               ],
               "weatherDesc":[
                  {
                     "value":"Sunny"
                  }
               ],
               "precipMM":"0.1",
               "humidity":"73",
               "visibility":"10",
               "pressure":"1020",
               "cloudcover":"16",
               "HeatIndexC":"28",
               "HeatIndexF":"82",
               "DewPointC":"20",
               "DewPointF":"69",
               "WindChillC":"26",
               "WindChillF":"78",
               "WindGustMiles":"21",
               "WindGustKmph":"34",
               "FeelsLikeC":"28",
               "FeelsLikeF":"82"
            }
         ]
      },
      {
         "date":"2017-04-03",
         "astronomy":[
            {
               "sunrise":"06:22 AM",
               "sunset":"06:47 PM",
               "moonrise":"12:20 PM",
               "moonset":"12:54 AM",
               "moon_phase":"First Quarter",
               "moon_illumination":"28"
            }
         ],
         "maxtempC":"28",
         "maxtempF":"83",
         "mintempC":"26",
         "mintempF":"78",
         "totalSnow_cm":"0.0",
         "sunHour":"0.0",
         "uvIndex":"0",
         "hourly":[
            {
               "time":"24",
               "tempC":"28",
               "tempF":"83",
               "windspeedMiles":"15",
               "windspeedKmph":"24",
               "winddirDegree":"77",
               "winddir16Point":"ENE",
               "weatherCode":"113",
               "weatherIconUrl":[
                  {
                     "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                  }
               ],
               "weatherDesc":[
                  {
                     "value":"Sunny"
                  }
               ],
               "precipMM":"0.1",
               "humidity":"73",
               "visibility":"10",
               "pressure":"1019",
               "cloudcover":"20",
               "HeatIndexC":"28",
               "HeatIndexF":"82",
               "DewPointC":"21",
               "DewPointF":"69",
               "WindChillC":"26",
               "WindChillF":"79",
               "WindGustMiles":"17",
               "WindGustKmph":"28",
               "FeelsLikeC":"28",
               "FeelsLikeF":"82"
            }
         ]
      },
      {
         "date":"2017-04-04",
         "astronomy":[
            {
               "sunrise":"06:21 AM",
               "sunset":"06:47 PM",
               "moonrise":"01:19 PM",
               "moonset":"01:50 AM",
               "moon_phase":"First Quarter",
               "moon_illumination":"34"
            }
         ],
         "maxtempC":"28",
         "maxtempF":"83",
         "mintempC":"25",
         "mintempF":"78",
         "totalSnow_cm":"0.0",
         "sunHour":"0.0",
         "uvIndex":"0",
         "hourly":[
            {
               "time":"24",
               "tempC":"28",
               "tempF":"83",
               "windspeedMiles":"14",
               "windspeedKmph":"23",
               "winddirDegree":"76",
               "winddir16Point":"ENE",
               "weatherCode":"113",
               "weatherIconUrl":[
                  {
                     "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                  }
               ],
               "weatherDesc":[
                  {
                     "value":"Sunny"
                  }
               ],
               "precipMM":"0.1",
               "humidity":"73",
               "visibility":"10",
               "pressure":"1018",
               "cloudcover":"26",
               "HeatIndexC":"28",
               "HeatIndexF":"82",
               "DewPointC":"21",
               "DewPointF":"69",
               "WindChillC":"26",
               "WindChillF":"78",
               "WindGustMiles":"17",
               "WindGustKmph":"27",
               "FeelsLikeC":"28",
               "FeelsLikeF":"82"
            }
         ]
      },
      {
         "date":"2017-04-05",
         "astronomy":[
            {
               "sunrise":"06:20 AM",
               "sunset":"06:48 PM",
               "moonrise":"02:16 PM",
               "moonset":"02:40 AM",
               "moon_phase":"First Quarter",
               "moon_illumination":"41"
            }
         ],
         "maxtempC":"28",
         "maxtempF":"83",
         "mintempC":"26",
         "mintempF":"78",
         "totalSnow_cm":"0.0",
         "sunHour":"0.0",
         "uvIndex":"0",
         "hourly":[
            {
               "time":"24",
               "tempC":"28",
               "tempF":"83",
               "windspeedMiles":"13",
               "windspeedKmph":"21",
               "winddirDegree":"71",
               "winddir16Point":"ENE",
               "weatherCode":"113",
               "weatherIconUrl":[
                  {
                     "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                  }
               ],
               "weatherDesc":[
                  {
                     "value":"Sunny"
                  }
               ],
               "precipMM":"0.2",
               "humidity":"74",
               "visibility":"10",
               "pressure":"1018",
               "cloudcover":"24",
               "HeatIndexC":"28",
               "HeatIndexF":"82",
               "DewPointC":"21",
               "DewPointF":"69",
               "WindChillC":"26",
               "WindChillF":"78",
               "WindGustMiles":"15",
               "WindGustKmph":"24",
               "FeelsLikeC":"28",
               "FeelsLikeF":"82"
            }
         ]
      },
      {
         "date":"2017-04-06",
         "astronomy":[
            {
               "sunrise":"06:19 AM",
               "sunset":"06:48 PM",
               "moonrise":"03:13 PM",
               "moonset":"03:28 AM",
               "moon_phase":"First Quarter",
               "moon_illumination":"48"
            }
         ],
         "maxtempC":"28",
         "maxtempF":"82",
         "mintempC":"25",
         "mintempF":"77",
         "totalSnow_cm":"0.0",
         "sunHour":"0.0",
         "uvIndex":"0",
         "hourly":[
            {
               "time":"24",
               "tempC":"28",
               "tempF":"82",
               "windspeedMiles":"13",
               "windspeedKmph":"21",
               "winddirDegree":"72",
               "winddir16Point":"ENE",
               "weatherCode":"113",
               "weatherIconUrl":[
                  {
                     "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                  }
               ],
               "weatherDesc":[
                  {
                     "value":"Sunny"
                  }
               ],
               "precipMM":"0.1",
               "humidity":"74",
               "visibility":"10",
               "pressure":"1018",
               "cloudcover":"20",
               "HeatIndexC":"27",
               "HeatIndexF":"81",
               "DewPointC":"20",
               "DewPointF":"69",
               "WindChillC":"25",
               "WindChillF":"78",
               "WindGustMiles":"15",
               "WindGustKmph":"25",
               "FeelsLikeC":"27",
               "FeelsLikeF":"81"
            }
         ]
      },
      {
         "date":"2017-04-07",
         "astronomy":[
            {
               "sunrise":"06:19 AM",
               "sunset":"06:48 PM",
               "moonrise":"04:07 PM",
               "moonset":"04:11 AM",
               "moon_phase":"Waxing Gibbous",
               "moon_illumination":"55"
            }
         ],
         "maxtempC":"28",
         "maxtempF":"83",
         "mintempC":"25",
         "mintempF":"77",
         "totalSnow_cm":"0.0",
         "sunHour":"0.0",
         "uvIndex":"0",
         "hourly":[
            {
               "time":"24",
               "tempC":"28",
               "tempF":"83",
               "windspeedMiles":"13",
               "windspeedKmph":"21",
               "winddirDegree":"77",
               "winddir16Point":"ENE",
               "weatherCode":"119",
               "weatherIconUrl":[
                  {
                     "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png"
                  }
               ],
               "weatherDesc":[
                  {
                     "value":"Cloudy"
                  }
               ],
               "precipMM":"0.4",
               "humidity":"75",
               "visibility":"9",
               "pressure":"1019",
               "cloudcover":"36",
               "HeatIndexC":"28",
               "HeatIndexF":"82",
               "DewPointC":"21",
               "DewPointF":"69",
               "WindChillC":"25",
               "WindChillF":"78",
               "WindGustMiles":"15",
               "WindGustKmph":"24",
               "FeelsLikeC":"28",
               "FeelsLikeF":"82"
            }
         ]
      },
      {
         "date":"2017-04-08",
         "astronomy":[
            {
               "sunrise":"06:18 AM",
               "sunset":"06:49 PM",
               "moonrise":"05:00 PM",
               "moonset":"04:52 AM",
               "moon_phase":"Waxing Gibbous",
               "moon_illumination":"62"
            }
         ],
         "maxtempC":"29",
         "maxtempF":"85",
         "mintempC":"26",
         "mintempF":"78",
         "totalSnow_cm":"0.0",
         "sunHour":"0.0",
         "uvIndex":"0",
         "hourly":[
            {
               "time":"24",
               "tempC":"29",
               "tempF":"85",
               "windspeedMiles":"6",
               "windspeedKmph":"9",
               "winddirDegree":"136",
               "winddir16Point":"SE",
               "weatherCode":"119",
               "weatherIconUrl":[
                  {
                     "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png"
                  }
               ],
               "weatherDesc":[
                  {
                     "value":"Cloudy"
                  }
               ],
               "precipMM":"0.7",
               "humidity":"75",
               "visibility":"10",
               "pressure":"1018",
               "cloudcover":"58",
               "HeatIndexC":"29",
               "HeatIndexF":"83",
               "DewPointC":"21",
               "DewPointF":"70",
               "WindChillC":"26",
               "WindChillF":"79",
               "WindGustMiles":"7",
               "WindGustKmph":"11",
               "FeelsLikeC":"29",
               "FeelsLikeF":"83"
            }
         ]
      },
      {
         "date":"2017-04-09",
         "astronomy":[
            {
               "sunrise":"06:17 AM",
               "sunset":"06:49 PM",
               "moonrise":"05:52 PM",
               "moonset":"05:31 AM",
               "moon_phase":"Waxing Gibbous",
               "moon_illumination":"69"
            }
         ],
         "maxtempC":"29",
         "maxtempF":"84",
         "mintempC":"25",
         "mintempF":"78",
         "totalSnow_cm":"0.0",
         "sunHour":"0.0",
         "uvIndex":"0",
         "hourly":[
            {
               "time":"24",
               "tempC":"29",
               "tempF":"84",
               "windspeedMiles":"4",
               "windspeedKmph":"7",
               "winddirDegree":"290",
               "winddir16Point":"WNW",
               "weatherCode":"353",
               "weatherIconUrl":[
                  {
                     "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png"
                  }
               ],
               "weatherDesc":[
                  {
                     "value":"Light rain shower"
                  }
               ],
               "precipMM":"0.7",
               "humidity":"74",
               "visibility":"10",
               "pressure":"1017",
               "cloudcover":"22",
               "HeatIndexC":"28",
               "HeatIndexF":"82",
               "DewPointC":"21",
               "DewPointF":"69",
               "WindChillC":"26",
               "WindChillF":"78",
               "WindGustMiles":"5",
               "WindGustKmph":"8",
               "FeelsLikeC":"28",
               "FeelsLikeF":"82"
            }
         ]
      }
   ]
}
let data2 = {
  "request":[
     {
        "type":"City",
        "query":"Honolulu, United States of America"
     }
  ],
  "weather":[
     {
        "date":"2018-04-02",
        "astronomy":[
           {
              "sunrise":"06:23 AM",
              "sunset":"06:47 PM",
              "moonrise":"09:11 PM",
              "moonset":"08:09 AM",
              "moon_phase":"Waning Gibbous",
              "moon_illumination":"97"
           }
        ],
        "maxtempC":"24",
        "maxtempF":"75",
        "mintempC":"22",
        "mintempF":"72",
        "totalSnow_cm":"0.0",
        "sunHour":"9.0",
        "uvIndex":"0",
        "hourly":[
           {
              "time":"0",
              "tempC":"22",
              "tempF":"72",
              "windspeedMiles":"6",
              "windspeedKmph":"9",
              "winddirDegree":"177",
              "winddir16Point":"S",
              "weatherCode":"353",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Light rain shower"
                 }
              ],
              "precipMM":"0.3",
              "humidity":"82",
              "visibility":"10",
              "pressure":"1015",
              "cloudcover":"47",
              "HeatIndexC":"25",
              "HeatIndexF":"77",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"23",
              "WindChillF":"74",
              "WindGustMiles":"8",
              "WindGustKmph":"13",
              "FeelsLikeC":"25",
              "FeelsLikeF":"77"
           },
           {
              "time":"100",
              "tempC":"22",
              "tempF":"72",
              "windspeedMiles":"6",
              "windspeedKmph":"10",
              "winddirDegree":"177",
              "winddir16Point":"S",
              "weatherCode":"353",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Light rain shower"
                 }
              ],
              "precipMM":"0.8",
              "humidity":"82",
              "visibility":"10",
              "pressure":"1014",
              "cloudcover":"54",
              "HeatIndexC":"25",
              "HeatIndexF":"77",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"23",
              "WindChillF":"73",
              "WindGustMiles":"9",
              "WindGustKmph":"15",
              "FeelsLikeC":"25",
              "FeelsLikeF":"77"
           },
           {
              "time":"200",
              "tempC":"22",
              "tempF":"72",
              "windspeedMiles":"7",
              "windspeedKmph":"11",
              "winddirDegree":"177",
              "winddir16Point":"S",
              "weatherCode":"356",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0026_heavy_rain_showers_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Moderate or heavy rain shower"
                 }
              ],
              "precipMM":"1.2",
              "humidity":"83",
              "visibility":"9",
              "pressure":"1014",
              "cloudcover":"60",
              "HeatIndexC":"25",
              "HeatIndexF":"77",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"23",
              "WindChillF":"73",
              "WindGustMiles":"10",
              "WindGustKmph":"17",
              "FeelsLikeC":"25",
              "FeelsLikeF":"77"
           },
           {
              "time":"300",
              "tempC":"22",
              "tempF":"72",
              "windspeedMiles":"7",
              "windspeedKmph":"12",
              "winddirDegree":"178",
              "winddir16Point":"S",
              "weatherCode":"356",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0026_heavy_rain_showers_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Moderate or heavy rain shower"
                 }
              ],
              "precipMM":"1.7",
              "humidity":"84",
              "visibility":"9",
              "pressure":"1013",
              "cloudcover":"67",
              "HeatIndexC":"25",
              "HeatIndexF":"77",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"23",
              "WindChillF":"73",
              "WindGustMiles":"11",
              "WindGustKmph":"18",
              "FeelsLikeC":"25",
              "FeelsLikeF":"77"
           },
           {
              "time":"400",
              "tempC":"23",
              "tempF":"73",
              "windspeedMiles":"8",
              "windspeedKmph":"12",
              "winddirDegree":"177",
              "winddir16Point":"S",
              "weatherCode":"356",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0026_heavy_rain_showers_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Moderate or heavy rain shower"
                 }
              ],
              "precipMM":"2.6",
              "humidity":"83",
              "visibility":"8",
              "pressure":"1013",
              "cloudcover":"71",
              "HeatIndexC":"25",
              "HeatIndexF":"77",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"23",
              "WindChillF":"73",
              "WindGustMiles":"13",
              "WindGustKmph":"21",
              "FeelsLikeC":"25",
              "FeelsLikeF":"77"
           },
           {
              "time":"500",
              "tempC":"23",
              "tempF":"73",
              "windspeedMiles":"8",
              "windspeedKmph":"13",
              "winddirDegree":"176",
              "winddir16Point":"S",
              "weatherCode":"356",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0026_heavy_rain_showers_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Moderate or heavy rain shower"
                 }
              ],
              "precipMM":"3.6",
              "humidity":"83",
              "visibility":"8",
              "pressure":"1013",
              "cloudcover":"76",
              "HeatIndexC":"25",
              "HeatIndexF":"77",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"23",
              "WindChillF":"74",
              "WindGustMiles":"14",
              "WindGustKmph":"23",
              "FeelsLikeC":"25",
              "FeelsLikeF":"77"
           },
           {
              "time":"600",
              "tempC":"23",
              "tempF":"73",
              "windspeedMiles":"9",
              "windspeedKmph":"14",
              "winddirDegree":"175",
              "winddir16Point":"S",
              "weatherCode":"356",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0026_heavy_rain_showers_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Moderate or heavy rain shower"
                 }
              ],
              "precipMM":"4.5",
              "humidity":"83",
              "visibility":"7",
              "pressure":"1013",
              "cloudcover":"81",
              "HeatIndexC":"25",
              "HeatIndexF":"78",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"23",
              "WindChillF":"74",
              "WindGustMiles":"15",
              "WindGustKmph":"25",
              "FeelsLikeC":"25",
              "FeelsLikeF":"78"
           },
           {
              "time":"700",
              "tempC":"23",
              "tempF":"74",
              "windspeedMiles":"10",
              "windspeedKmph":"15",
              "winddirDegree":"179",
              "winddir16Point":"S",
              "weatherCode":"356",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0010_heavy_rain_showers.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Moderate or heavy rain shower"
                 }
              ],
              "precipMM":"4.5",
              "humidity":"82",
              "visibility":"7",
              "pressure":"1013",
              "cloudcover":"78",
              "HeatIndexC":"26",
              "HeatIndexF":"78",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"23",
              "WindChillF":"74",
              "WindGustMiles":"16",
              "WindGustKmph":"26",
              "FeelsLikeC":"26",
              "FeelsLikeF":"78"
           },
           {
              "time":"800",
              "tempC":"23",
              "tempF":"74",
              "windspeedMiles":"10",
              "windspeedKmph":"16",
              "winddirDegree":"182",
              "winddir16Point":"S",
              "weatherCode":"353",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Light rain shower"
                 }
              ],
              "precipMM":"4.4",
              "humidity":"81",
              "visibility":"8",
              "pressure":"1013",
              "cloudcover":"74",
              "HeatIndexC":"26",
              "HeatIndexF":"78",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"24",
              "WindChillF":"74",
              "WindGustMiles":"17",
              "WindGustKmph":"27",
              "FeelsLikeC":"26",
              "FeelsLikeF":"78"
           },
           {
              "time":"900",
              "tempC":"24",
              "tempF":"74",
              "windspeedMiles":"11",
              "windspeedKmph":"17",
              "winddirDegree":"185",
              "winddir16Point":"S",
              "weatherCode":"353",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Light rain shower"
                 }
              ],
              "precipMM":"4.4",
              "humidity":"81",
              "visibility":"8",
              "pressure":"1014",
              "cloudcover":"71",
              "HeatIndexC":"26",
              "HeatIndexF":"78",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"24",
              "WindChillF":"75",
              "WindGustMiles":"17",
              "WindGustKmph":"28",
              "FeelsLikeC":"26",
              "FeelsLikeF":"78"
           },
           {
              "time":"1000",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"11",
              "windspeedKmph":"18",
              "winddirDegree":"192",
              "winddir16Point":"SSW",
              "weatherCode":"353",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Light rain shower"
                 }
              ],
              "precipMM":"3.2",
              "humidity":"80",
              "visibility":"9",
              "pressure":"1013",
              "cloudcover":"67",
              "HeatIndexC":"26",
              "HeatIndexF":"78",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"24",
              "WindChillF":"75",
              "WindGustMiles":"17",
              "WindGustKmph":"27",
              "FeelsLikeC":"26",
              "FeelsLikeF":"78"
           },
           {
              "time":"1100",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"11",
              "windspeedKmph":"18",
              "winddirDegree":"200",
              "winddir16Point":"SSW",
              "weatherCode":"293",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0017_cloudy_with_light_rain.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Patchy light rain"
                 }
              ],
              "precipMM":"2.1",
              "humidity":"80",
              "visibility":"9",
              "pressure":"1013",
              "cloudcover":"64",
              "HeatIndexC":"26",
              "HeatIndexF":"78",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"24",
              "WindChillF":"75",
              "WindGustMiles":"16",
              "WindGustKmph":"26",
              "FeelsLikeC":"26",
              "FeelsLikeF":"78"
           },
           {
              "time":"1200",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"12",
              "windspeedKmph":"19",
              "winddirDegree":"208",
              "winddir16Point":"SSW",
              "weatherCode":"293",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0017_cloudy_with_light_rain.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Patchy light rain"
                 }
              ],
              "precipMM":"0.9",
              "humidity":"80",
              "visibility":"10",
              "pressure":"1013",
              "cloudcover":"60",
              "HeatIndexC":"26",
              "HeatIndexF":"78",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"24",
              "WindChillF":"75",
              "WindGustMiles":"16",
              "WindGustKmph":"25",
              "FeelsLikeC":"26",
              "FeelsLikeF":"78"
           },
           {
              "time":"1300",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"12",
              "windspeedKmph":"19",
              "winddirDegree":"215",
              "winddir16Point":"SW",
              "weatherCode":"293",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0017_cloudy_with_light_rain.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Patchy light rain"
                 }
              ],
              "precipMM":"1.5",
              "humidity":"81",
              "visibility":"9",
              "pressure":"1013",
              "cloudcover":"67",
              "HeatIndexC":"25",
              "HeatIndexF":"78",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"23",
              "WindChillF":"74",
              "WindGustMiles":"16",
              "WindGustKmph":"26",
              "FeelsLikeC":"25",
              "FeelsLikeF":"78"
           },
           {
              "time":"1400",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"12",
              "windspeedKmph":"19",
              "winddirDegree":"222",
              "winddir16Point":"SW",
              "weatherCode":"302",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0018_cloudy_with_heavy_rain.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Moderate rain"
                 }
              ],
              "precipMM":"2.0",
              "humidity":"82",
              "visibility":"9",
              "pressure":"1012",
              "cloudcover":"73",
              "HeatIndexC":"25",
              "HeatIndexF":"77",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"23",
              "WindChillF":"74",
              "WindGustMiles":"17",
              "WindGustKmph":"27",
              "FeelsLikeC":"25",
              "FeelsLikeF":"77"
           },
           {
              "time":"1500",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"12",
              "windspeedKmph":"19",
              "winddirDegree":"230",
              "winddir16Point":"SW",
              "weatherCode":"302",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0018_cloudy_with_heavy_rain.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Moderate rain"
                 }
              ],
              "precipMM":"2.6",
              "humidity":"83",
              "visibility":"8",
              "pressure":"1011",
              "cloudcover":"80",
              "HeatIndexC":"25",
              "HeatIndexF":"77",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"23",
              "WindChillF":"73",
              "WindGustMiles":"17",
              "WindGustKmph":"27",
              "FeelsLikeC":"25",
              "FeelsLikeF":"77"
           },
           {
              "time":"1600",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"11",
              "windspeedKmph":"17",
              "winddirDegree":"236",
              "winddir16Point":"WSW",
              "weatherCode":"302",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0018_cloudy_with_heavy_rain.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Moderate rain"
                 }
              ],
              "precipMM":"3.5",
              "humidity":"85",
              "visibility":"8",
              "pressure":"1011",
              "cloudcover":"84",
              "HeatIndexC":"24",
              "HeatIndexF":"76",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"22",
              "WindChillF":"72",
              "WindGustMiles":"16",
              "WindGustKmph":"25",
              "FeelsLikeC":"24",
              "FeelsLikeF":"76"
           },
           {
              "time":"1700",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"9",
              "windspeedKmph":"15",
              "winddirDegree":"243",
              "winddir16Point":"WSW",
              "weatherCode":"299",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0010_heavy_rain_showers.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Moderate rain at times"
                 }
              ],
              "precipMM":"4.5",
              "humidity":"86",
              "visibility":"8",
              "pressure":"1011",
              "cloudcover":"88",
              "HeatIndexC":"24",
              "HeatIndexF":"75",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"21",
              "WindChillF":"71",
              "WindGustMiles":"14",
              "WindGustKmph":"23",
              "FeelsLikeC":"24",
              "FeelsLikeF":"75"
           },
           {
              "time":"1800",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"8",
              "windspeedKmph":"13",
              "winddirDegree":"249",
              "winddir16Point":"WSW",
              "weatherCode":"299",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0026_heavy_rain_showers_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Moderate rain at times"
                 }
              ],
              "precipMM":"5.4",
              "humidity":"87",
              "visibility":"7",
              "pressure":"1011",
              "cloudcover":"93",
              "HeatIndexC":"23",
              "HeatIndexF":"74",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"21",
              "WindChillF":"69",
              "WindGustMiles":"13",
              "WindGustKmph":"21",
              "FeelsLikeC":"23",
              "FeelsLikeF":"74"
           },
           {
              "time":"1900",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"8",
              "windspeedKmph":"13",
              "winddirDegree":"249",
              "winddir16Point":"WSW",
              "weatherCode":"299",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0026_heavy_rain_showers_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Moderate rain at times"
                 }
              ],
              "precipMM":"5.0",
              "humidity":"87",
              "visibility":"8",
              "pressure":"1011",
              "cloudcover":"84",
              "HeatIndexC":"22",
              "HeatIndexF":"72",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"20",
              "WindChillF":"67",
              "WindGustMiles":"12",
              "WindGustKmph":"20",
              "FeelsLikeC":"22",
              "FeelsLikeF":"72"
           },
           {
              "time":"2000",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"8",
              "windspeedKmph":"12",
              "winddirDegree":"249",
              "winddir16Point":"WSW",
              "weatherCode":"116",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Partly cloudy"
                 }
              ],
              "precipMM":"4.6",
              "humidity":"86",
              "visibility":"8",
              "pressure":"1011",
              "cloudcover":"76",
              "HeatIndexC":"21",
              "HeatIndexF":"70",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"19",
              "WindChillF":"65",
              "WindGustMiles":"12",
              "WindGustKmph":"19",
              "FeelsLikeC":"21",
              "FeelsLikeF":"70"
           },
           {
              "time":"2100",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"7",
              "windspeedKmph":"12",
              "winddirDegree":"248",
              "winddir16Point":"WSW",
              "weatherCode":"116",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Partly cloudy"
                 }
              ],
              "precipMM":"4.2",
              "humidity":"86",
              "visibility":"9",
              "pressure":"1011",
              "cloudcover":"67",
              "HeatIndexC":"20",
              "HeatIndexF":"68",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"17",
              "WindChillF":"63",
              "WindGustMiles":"11",
              "WindGustKmph":"18",
              "FeelsLikeC":"20",
              "FeelsLikeF":"68"
           },
           {
              "time":"2200",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"7",
              "windspeedKmph":"11",
              "winddirDegree":"250",
              "winddir16Point":"WSW",
              "weatherCode":"116",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Partly cloudy"
                 }
              ],
              "precipMM":"2.8",
              "humidity":"86",
              "visibility":"9",
              "pressure":"1011",
              "cloudcover":"56",
              "HeatIndexC":"21",
              "HeatIndexF":"69",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"18",
              "WindChillF":"64",
              "WindGustMiles":"11",
              "WindGustKmph":"18",
              "FeelsLikeC":"21",
              "FeelsLikeF":"69"
           },
           {
              "time":"2300",
              "tempC":"24",
              "tempF":"75",
              "windspeedMiles":"7",
              "windspeedKmph":"11",
              "winddirDegree":"252",
              "winddir16Point":"WSW",
              "weatherCode":"116",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Partly cloudy"
                 }
              ],
              "precipMM":"1.4",
              "humidity":"86",
              "visibility":"10",
              "pressure":"1011",
              "cloudcover":"45",
              "HeatIndexC":"21",
              "HeatIndexF":"70",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"18",
              "WindChillF":"64",
              "WindGustMiles":"11",
              "WindGustKmph":"18",
              "FeelsLikeC":"21",
              "FeelsLikeF":"70"
           }
        ]
     }
  ]
}
let data3 = {
  "request":[
     {
        "type":"City",
        "query":"Honolulu, United States of America"
     }
  ],
  "weather":[
     {
        "date":"2017-04-02",
        "astronomy":[
           {
              "sunrise":"06:23 AM",
              "sunset":"06:47 PM",
              "moonrise":"11:23 AM",
              "moonset":"No moonset",
              "moon_phase":"Waxing Crescent",
              "moon_illumination":"21"
           }
        ],
        "maxtempC":"29",
        "maxtempF":"84",
        "mintempC":"25",
        "mintempF":"76",
        "totalSnow_cm":"0.0",
        "sunHour":"12.0",
        "uvIndex":"0",
        "hourly":[
           {
              "time":"0",
              "tempC":"25",
              "tempF":"76",
              "windspeedMiles":"17",
              "windspeedKmph":"28",
              "winddirDegree":"80",
              "winddir16Point":"E",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Clear"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"77",
              "visibility":"10",
              "pressure":"1021",
              "cloudcover":"8",
              "HeatIndexC":"26",
              "HeatIndexF":"80",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"25",
              "WindChillF":"76",
              "WindGustMiles":"20",
              "WindGustKmph":"32",
              "FeelsLikeC":"26",
              "FeelsLikeF":"80"
           },
           {
              "time":"100",
              "tempC":"25",
              "tempF":"77",
              "windspeedMiles":"17",
              "windspeedKmph":"27",
              "winddirDegree":"79",
              "winddir16Point":"ENE",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Clear"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"77",
              "visibility":"10",
              "pressure":"1020",
              "cloudcover":"9",
              "HeatIndexC":"26",
              "HeatIndexF":"79",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"24",
              "WindChillF":"75",
              "WindGustMiles":"20",
              "WindGustKmph":"32",
              "FeelsLikeC":"26",
              "FeelsLikeF":"79"
           },
           {
              "time":"200",
              "tempC":"25",
              "tempF":"77",
              "windspeedMiles":"17",
              "windspeedKmph":"27",
              "winddirDegree":"77",
              "winddir16Point":"ENE",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Clear"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"77",
              "visibility":"10",
              "pressure":"1020",
              "cloudcover":"11",
              "HeatIndexC":"26",
              "HeatIndexF":"78",
              "DewPointC":"19",
              "DewPointF":"67",
              "WindChillC":"24",
              "WindChillF":"75",
              "WindGustMiles":"20",
              "WindGustKmph":"32",
              "FeelsLikeC":"26",
              "FeelsLikeF":"78"
           },
           {
              "time":"300",
              "tempC":"25",
              "tempF":"77",
              "windspeedMiles":"16",
              "windspeedKmph":"26",
              "winddirDegree":"76",
              "winddir16Point":"ENE",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Clear"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"77",
              "visibility":"10",
              "pressure":"1020",
              "cloudcover":"12",
              "HeatIndexC":"25",
              "HeatIndexF":"78",
              "DewPointC":"19",
              "DewPointF":"66",
              "WindChillC":"23",
              "WindChillF":"74",
              "WindGustMiles":"19",
              "WindGustKmph":"31",
              "FeelsLikeC":"25",
              "FeelsLikeF":"78"
           },
           {
              "time":"400",
              "tempC":"26",
              "tempF":"78",
              "windspeedMiles":"17",
              "windspeedKmph":"27",
              "winddirDegree":"75",
              "winddir16Point":"ENE",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Clear"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"76",
              "visibility":"10",
              "pressure":"1020",
              "cloudcover":"16",
              "HeatIndexC":"25",
              "HeatIndexF":"78",
              "DewPointC":"19",
              "DewPointF":"66",
              "WindChillC":"23",
              "WindChillF":"74",
              "WindGustMiles":"20",
              "WindGustKmph":"32",
              "FeelsLikeC":"25",
              "FeelsLikeF":"78"
           },
           {
              "time":"500",
              "tempC":"26",
              "tempF":"79",
              "windspeedMiles":"17",
              "windspeedKmph":"27",
              "winddirDegree":"75",
              "winddir16Point":"ENE",
              "weatherCode":"116",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Partly cloudy"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"76",
              "visibility":"10",
              "pressure":"1020",
              "cloudcover":"20",
              "HeatIndexC":"25",
              "HeatIndexF":"78",
              "DewPointC":"19",
              "DewPointF":"66",
              "WindChillC":"23",
              "WindChillF":"74",
              "WindGustMiles":"21",
              "WindGustKmph":"33",
              "FeelsLikeC":"25",
              "FeelsLikeF":"78"
           },
           {
              "time":"600",
              "tempC":"27",
              "tempF":"80",
              "windspeedMiles":"17",
              "windspeedKmph":"28",
              "winddirDegree":"74",
              "winddir16Point":"ENE",
              "weatherCode":"116",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Partly cloudy"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"76",
              "visibility":"10",
              "pressure":"1020",
              "cloudcover":"24",
              "HeatIndexC":"26",
              "HeatIndexF":"78",
              "DewPointC":"19",
              "DewPointF":"66",
              "WindChillC":"24",
              "WindChillF":"74",
              "WindGustMiles":"21",
              "WindGustKmph":"34",
              "FeelsLikeC":"26",
              "FeelsLikeF":"78"
           },
           {
              "time":"700",
              "tempC":"27",
              "tempF":"80",
              "windspeedMiles":"18",
              "windspeedKmph":"29",
              "winddirDegree":"76",
              "winddir16Point":"ENE",
              "weatherCode":"116",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Partly cloudy"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"74",
              "visibility":"10",
              "pressure":"1020",
              "cloudcover":"22",
              "HeatIndexC":"26",
              "HeatIndexF":"79",
              "DewPointC":"19",
              "DewPointF":"66",
              "WindChillC":"24",
              "WindChillF":"75",
              "WindGustMiles":"22",
              "WindGustKmph":"35",
              "FeelsLikeC":"26",
              "FeelsLikeF":"79"
           },
           {
              "time":"800",
              "tempC":"27",
              "tempF":"81",
              "windspeedMiles":"19",
              "windspeedKmph":"30",
              "winddirDegree":"77",
              "winddir16Point":"ENE",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Sunny"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"72",
              "visibility":"10",
              "pressure":"1021",
              "cloudcover":"21",
              "HeatIndexC":"27",
              "HeatIndexF":"80",
              "DewPointC":"19",
              "DewPointF":"67",
              "WindChillC":"25",
              "WindChillF":"77",
              "WindGustMiles":"22",
              "WindGustKmph":"35",
              "FeelsLikeC":"27",
              "FeelsLikeF":"80"
           },
           {
              "time":"900",
              "tempC":"28",
              "tempF":"82",
              "windspeedMiles":"19",
              "windspeedKmph":"31",
              "winddirDegree":"79",
              "winddir16Point":"ENE",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Sunny"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"70",
              "visibility":"10",
              "pressure":"1021",
              "cloudcover":"19",
              "HeatIndexC":"27",
              "HeatIndexF":"81",
              "DewPointC":"20",
              "DewPointF":"67",
              "WindChillC":"25",
              "WindChillF":"78",
              "WindGustMiles":"22",
              "WindGustKmph":"36",
              "FeelsLikeC":"27",
              "FeelsLikeF":"81"
           },
           {
              "time":"1000",
              "tempC":"28",
              "tempF":"82",
              "windspeedMiles":"19",
              "windspeedKmph":"31",
              "winddirDegree":"80",
              "winddir16Point":"E",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Sunny"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"68",
              "visibility":"10",
              "pressure":"1021",
              "cloudcover":"12",
              "HeatIndexC":"28",
              "HeatIndexF":"82",
              "DewPointC":"20",
              "DewPointF":"67",
              "WindChillC":"26",
              "WindChillF":"79",
              "WindGustMiles":"22",
              "WindGustKmph":"36",
              "FeelsLikeC":"28",
              "FeelsLikeF":"82"
           },
           {
              "time":"1100",
              "tempC":"28",
              "tempF":"83",
              "windspeedMiles":"19",
              "windspeedKmph":"31",
              "winddirDegree":"81",
              "winddir16Point":"E",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Sunny"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"66",
              "visibility":"10",
              "pressure":"1021",
              "cloudcover":"6",
              "HeatIndexC":"29",
              "HeatIndexF":"84",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"27",
              "WindChillF":"80",
              "WindGustMiles":"22",
              "WindGustKmph":"36",
              "FeelsLikeC":"29",
              "FeelsLikeF":"84"
           },
           {
              "time":"1200",
              "tempC":"29",
              "tempF":"84",
              "windspeedMiles":"19",
              "windspeedKmph":"31",
              "winddirDegree":"82",
              "winddir16Point":"E",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Sunny"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"64",
              "visibility":"10",
              "pressure":"1021",
              "cloudcover":"0",
              "HeatIndexC":"30",
              "HeatIndexF":"85",
              "DewPointC":"20",
              "DewPointF":"68",
              "WindChillC":"28",
              "WindChillF":"82",
              "WindGustMiles":"22",
              "WindGustKmph":"36",
              "FeelsLikeC":"30",
              "FeelsLikeF":"85"
           },
           {
              "time":"1300",
              "tempC":"29",
              "tempF":"83",
              "windspeedMiles":"19",
              "windspeedKmph":"31",
              "winddirDegree":"80",
              "winddir16Point":"E",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Sunny"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"65",
              "visibility":"10",
              "pressure":"1020",
              "cloudcover":"1",
              "HeatIndexC":"30",
              "HeatIndexF":"86",
              "DewPointC":"21",
              "DewPointF":"69",
              "WindChillC":"28",
              "WindChillF":"82",
              "WindGustMiles":"22",
              "WindGustKmph":"35",
              "FeelsLikeC":"30",
              "FeelsLikeF":"86"
           },
           {
              "time":"1400",
              "tempC":"28",
              "tempF":"83",
              "windspeedMiles":"19",
              "windspeedKmph":"30",
              "winddirDegree":"77",
              "winddir16Point":"ENE",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Sunny"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"66",
              "visibility":"10",
              "pressure":"1020",
              "cloudcover":"3",
              "HeatIndexC":"31",
              "HeatIndexF":"87",
              "DewPointC":"21",
              "DewPointF":"70",
              "WindChillC":"28",
              "WindChillF":"82",
              "WindGustMiles":"22",
              "WindGustKmph":"35",
              "FeelsLikeC":"31",
              "FeelsLikeF":"87"
           },
           {
              "time":"1500",
              "tempC":"28",
              "tempF":"83",
              "windspeedMiles":"19",
              "windspeedKmph":"30",
              "winddirDegree":"75",
              "winddir16Point":"ENE",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Sunny"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"67",
              "visibility":"10",
              "pressure":"1019",
              "cloudcover":"4",
              "HeatIndexC":"31",
              "HeatIndexF":"88",
              "DewPointC":"22",
              "DewPointF":"71",
              "WindChillC":"28",
              "WindChillF":"83",
              "WindGustMiles":"22",
              "WindGustKmph":"35",
              "FeelsLikeC":"31",
              "FeelsLikeF":"88"
           },
           {
              "time":"1600",
              "tempC":"28",
              "tempF":"82",
              "windspeedMiles":"19",
              "windspeedKmph":"30",
              "winddirDegree":"73",
              "winddir16Point":"ENE",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Sunny"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"70",
              "visibility":"10",
              "pressure":"1019",
              "cloudcover":"8",
              "HeatIndexC":"31",
              "HeatIndexF":"87",
              "DewPointC":"22",
              "DewPointF":"71",
              "WindChillC":"28",
              "WindChillF":"82",
              "WindGustMiles":"22",
              "WindGustKmph":"35",
              "FeelsLikeC":"31",
              "FeelsLikeF":"87"
           },
           {
              "time":"1700",
              "tempC":"28",
              "tempF":"82",
              "windspeedMiles":"19",
              "windspeedKmph":"30",
              "winddirDegree":"71",
              "winddir16Point":"ENE",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Sunny"
                 }
              ],
              "precipMM":"0.1",
              "humidity":"72",
              "visibility":"10",
              "pressure":"1019",
              "cloudcover":"12",
              "HeatIndexC":"30",
              "HeatIndexF":"86",
              "DewPointC":"22",
              "DewPointF":"71",
              "WindChillC":"27",
              "WindChillF":"81",
              "WindGustMiles":"22",
              "WindGustKmph":"35",
              "FeelsLikeC":"30",
              "FeelsLikeF":"86"
           },
           {
              "time":"1800",
              "tempC":"27",
              "tempF":"81",
              "windspeedMiles":"19",
              "windspeedKmph":"30",
              "winddirDegree":"69",
              "winddir16Point":"ENE",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Clear"
                 }
              ],
              "precipMM":"0.1",
              "humidity":"75",
              "visibility":"10",
              "pressure":"1019",
              "cloudcover":"16",
              "HeatIndexC":"30",
              "HeatIndexF":"85",
              "DewPointC":"22",
              "DewPointF":"72",
              "WindChillC":"27",
              "WindChillF":"80",
              "WindGustMiles":"21",
              "WindGustKmph":"35",
              "FeelsLikeC":"30",
              "FeelsLikeF":"85"
           },
           {
              "time":"1900",
              "tempC":"27",
              "tempF":"80",
              "windspeedMiles":"18",
              "windspeedKmph":"30",
              "winddirDegree":"71",
              "winddir16Point":"ENE",
              "weatherCode":"113",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Clear"
                 }
              ],
              "precipMM":"0.1",
              "humidity":"77",
              "visibility":"10",
              "pressure":"1019",
              "cloudcover":"20",
              "HeatIndexC":"29",
              "HeatIndexF":"84",
              "DewPointC":"22",
              "DewPointF":"72",
              "WindChillC":"26",
              "WindChillF":"79",
              "WindGustMiles":"21",
              "WindGustKmph":"34",
              "FeelsLikeC":"29",
              "FeelsLikeF":"84"
           },
           {
              "time":"2000",
              "tempC":"27",
              "tempF":"80",
              "windspeedMiles":"18",
              "windspeedKmph":"29",
              "winddirDegree":"72",
              "winddir16Point":"ENE",
              "weatherCode":"116",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Partly cloudy"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"78",
              "visibility":"10",
              "pressure":"1019",
              "cloudcover":"24",
              "HeatIndexC":"28",
              "HeatIndexF":"83",
              "DewPointC":"22",
              "DewPointF":"71",
              "WindChillC":"26",
              "WindChillF":"79",
              "WindGustMiles":"21",
              "WindGustKmph":"34",
              "FeelsLikeC":"28",
              "FeelsLikeF":"83"
           },
           {
              "time":"2100",
              "tempC":"26",
              "tempF":"79",
              "windspeedMiles":"18",
              "windspeedKmph":"29",
              "winddirDegree":"74",
              "winddir16Point":"ENE",
              "weatherCode":"116",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Partly cloudy"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"80",
              "visibility":"10",
              "pressure":"1019",
              "cloudcover":"28",
              "HeatIndexC":"28",
              "HeatIndexF":"82",
              "DewPointC":"22",
              "DewPointF":"71",
              "WindChillC":"26",
              "WindChillF":"78",
              "WindGustMiles":"21",
              "WindGustKmph":"33",
              "FeelsLikeC":"28",
              "FeelsLikeF":"82"
           },
           {
              "time":"2200",
              "tempC":"26",
              "tempF":"79",
              "windspeedMiles":"18",
              "windspeedKmph":"28",
              "winddirDegree":"75",
              "winddir16Point":"ENE",
              "weatherCode":"116",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Partly cloudy"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"80",
              "visibility":"10",
              "pressure":"1019",
              "cloudcover":"34",
              "HeatIndexC":"27",
              "HeatIndexF":"81",
              "DewPointC":"22",
              "DewPointF":"71",
              "WindChillC":"25",
              "WindChillF":"77",
              "WindGustMiles":"20",
              "WindGustKmph":"33",
              "FeelsLikeC":"27",
              "FeelsLikeF":"81"
           },
           {
              "time":"2300",
              "tempC":"26",
              "tempF":"78",
              "windspeedMiles":"17",
              "windspeedKmph":"28",
              "winddirDegree":"76",
              "winddir16Point":"ENE",
              "weatherCode":"119",
              "weatherIconUrl":[
                 {
                    "value":"http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png"
                 }
              ],
              "weatherDesc":[
                 {
                    "value":"Cloudy"
                 }
              ],
              "precipMM":"0.0",
              "humidity":"80",
              "visibility":"10",
              "pressure":"1019",
              "cloudcover":"40",
              "HeatIndexC":"27",
              "HeatIndexF":"81",
              "DewPointC":"21",
              "DewPointF":"70",
              "WindChillC":"25",
              "WindChillF":"77",
              "WindGustMiles":"20",
              "WindGustKmph":"32",
              "FeelsLikeC":"27",
              "FeelsLikeF":"81"
           }
        ]
     }
  ]
}

let tempdata = [
  data1,
  data2,
  data3
]
